language: go

go:
  - "1.10"
  - "tip"

services:
  - redis-server

install:
  - make depend
  - make configure

script:
  - make test
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
